# target programming lamguage
language: java

# JDK versios support
jdk:
  #- oraclejdk7
  - oraclejdk8

# run tests, findbugs, pmd and friends using Ant, Maven or Gradle
script: cd core && mvn test install